version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8005:8005"
    volumes:
      - .:/app  
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5434/mydatabase
    depends_on:
      - db

  # PostgreSQL
  db:
    image: postgres:13
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
