"""removed  contributors m2m table

Revision ID: 869257b806ad
Revises: c163560479da
Create Date: 2025-01-16 00:55:49.600662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869257b806ad'
down_revision: Union[str, None] = 'c163560479da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_contributors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_contributors',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_contributors_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='project_contributors_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name='project_contributors_pkey')
    )
    # ### end Alembic commands ###
